name: Starter transformation
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: ai-chat-history
    required: false
  - name: kafka_username
    inputType: Secret
    description: ''
    defaultValue: ''
    required: false
  - name: kafka_password
    inputType: Secret
    description: ''
    defaultValue: ''
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
