name: Machine Generator
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: machine-generator-output
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
